### ISSUE TITLE
Riddle number 6 does not check for parallelism

### ISSUE THREAD

**Issue by pkafel** [vanniktech/RxRiddles#4]
Hey,

There is a small problem with riddle number 6 and it is up to you guys how you want to solve it. In the task description there is mentioned that 

> Execute both [first] and [second] Single's in parallel...

however you solution works sequentially. Thats because there are no schedulers running on mentioned Singles which means everything executes on main thread. Test is passing because it is not really checking for parallelism. If you would want to do that you could

```kotlin
val first = Single.timer(5, SECONDS, rxRule)
        .map { 10 }
        .doOnSubscribe { subscribeCounter.incrementAndGet() }

val second = Single.timer(3, SECONDS, rxRule)
        .map { 5 }
        .doOnSubscribe { subscribeCounter.incrementAndGet() }

// rest of the test goes here...

rxRule.advanceTimeBy(4, SECONDS)

// check if second already finished and the first one did not
first.test().assertNotComplete()
second.test().assertComplete()

```

You get the idea. So if the intention was to check for parallelism you need to adjust solution. If solution is good then you need to adjust the description.

**Comment by vanniktech** [comment]
I don't quite understand the problem.

RxRule is having a Scheduler that will run. The essential part is that subscribe is called eagerly. Which is asserted with `assertEmpty()` & `assertThat(subscribeCounter.get()).isEqualTo(2) // We want to subscribe immediately.`

**Comment by vanniktech** [comment]
I'm going to close this for now as I don't see a reason to change this. If you feel otherwise feel free to message me again.

**Comment by lwasylkowski** [comment]
@vanniktech I'll message here since I had similar thoughts when doing riddle no 6.

The point is, the solution proposed:

```kotlin
object Riddle6Solution {
  fun solve(first: Single<Int>, second: Single<Int>)
      = Single.zip(first, second, BiFunction<Int, Int, Pair<Int, Int>> { t1, t2 -> t1 to t2 })
}
```

does not introduce any parallelism. The comment states:
> Execute both [first] and [second] Single's in parallel and provide both results as a pair.
but the solution does not execute _any arbitrary pair of singles_ in parallel. On the contrary, as long as `first` and `single` doesn't specify schedulers, the solution works sequentially. The solution is appropriate only for this specific use case (implemented in tests), where singles already work on separate scheduler(s).

For actual educational value I'd expect that the provided singles don't have schedulers applied. I believe this is one of the things that are surprising for the beginners: in order to have the two streams work in parallel, we need to move them off the main thread manually, while the riddle suggests otherwise

**Comment by vanniktech** [comment]
Yup, that's right! Should we add a sentence to the documentation that we can assume that each `Single` has already a Scheduler applied? Or how do you want to proceed?

**Comment by lwasyl** [comment]
@vanniktech took me a while to find time for this, [here](https://github.com/vanniktech/RxRiddles/pull/20) is my suggestion. I believe not providing a scheduler and not changing the comment is the way to go for this to still be a `riddle` ;) Let me know what you think
